---
{% raw -%}
- name: Teardown
  hosts: localhost
  connection: local
  gather_facts: False
  no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"
  vars:
    molecule_file: "{{ lookup('env','MOLECULE_FILE') }}"
    molecule_yml: "{{ lookup('file', molecule_file) | from_yaml }}"
  tasks:
    # FIXME: This won't scale.
    # FIXME: This will kill all origin containers on this host,
    # FIXME: including containers we did not create.
    - name: check for origin instances
      command: docker ps -q -f name=k8s -f name=origin
      register: docker_ps_result

    - name: Destroy origin instance(s)
      docker_container:
        name: "{{ item }}"
        state: absent
        force_kill: True
      with_items: "{{ docker_ps_result.stdout_lines }}"

    - name: Destroy molecule instance(s)
      docker_container:
        name: "{{ item.name }}"
        state: absent
        force_kill: "{{ item.force_kill | default(True) }}"
      with_items: "{{ molecule_yml.platforms }}"
{%- endraw %}
